### ISSUE TITLE
Serialize & Deserialize Validators? 

### ISSUE THREAD

**Issue by speigg** [Blu-J/ts-matches#499]
Is it feasible/easy to serialize and deserialize Validators? 

I noticed `parserAsString` api, which seems like the serialization part. 

Just wondering if there is anything like `parserFromString` (existing or planned)

**Comment by Blu-J** [comment]
I would love having that. There are ideas that I share the parsing/ validation with a client. 
I have a library that is trying to deserialize from [JSON schema](https://json-schema.org/) https://github.com/Blu-J/ts-validate-json-schema And going to JSON schema is easier than parsing (I need to update that lib). 
I also have a parsers into typescript types. https://github.com/Blu-J/ts-matches/blob/master/src/transformers/typescript-types.ts
But nothing that is a round trip yet. 

For this feature, I would like something that serializes close to Typescript like.
Will need a test for each of the types, round trips.

**Comment by Blu-J** [comment]
@speigg Do you have any ideas?
Does making the above library serialize validators sound good?
What about the cases of manual functions?
What other edge cases. Or should we just do the simple types like the json schema?

**Comment by speigg** [comment]
Serializing validators to/from typescript types would be really cool!

**Comment by Blu-J** [comment]
I have the to schema and back, following a spec
https://npm.runkit.com/ts-matches-json-schema
https://github.com/Blu-J/ts-matches-json-schema
If you want to flesh out more of the generation to + from typescript, I would love a pr or something but I can't think of how to get it working.

Going to close because I have a serialization and deserialization. I don't know how to work on the typescript deserialization and serialization, it was too flaky and only useful in builds in nodejs and nowhere else.

**Comment by Blu-J** [comment]
https://app.bountysource.com/issues/105401775-serialize-deserialize-validators

**Comment by Blu-J** [comment]
Forgot to point out, but I put up a bounty for this bug since I didn't have a solution to this. I think I started out, but couldn't solve it 100%. https://github.com/Blu-J/ts-matches/blob/master/src/transformers/typescript-types.ts
And the types going out are close with the describer for the error messages. I will try and hold the types for the output, but I have also made it extendable too.

**Comment by ucefkh** [comment]
Is this still active?

**Comment by Blu-J** [comment]
The bounty is active, but I'm not working on this. I'll leave the way it stringifies the Matchers, but maybe having other opinions then locking it down would help. 
And as for the story of serialization/ de-serialization I use the https://github.com/Blu-J/ts-matches-json-schema/ which serializes the Matchers using the JSON schema specifications. 

As for this project, I still use it at work, but as it stabilized I need to change it less and less.

**Comment by pczarn** [comment]
Hi. I am a 27 year old programmer.

I have 2+ years of experience with parsing algorithms.

Is it OK to add a heavy typescript parser such as @babel/parser as a dependency, or should the solution contain, say, a custom recursive descent parser?

Unfortunately, Ethereum prices fell significantly since the bounty was posted. @Blu-J are you willing to double the bounty? If so, I would solve this issue.

--Peter

**Comment by Blu-J** [comment]
Well, I kinda don't want it to pollute this library. If this was implemented then I would keep it a seperate lib, I love so if so do it like ts-matches-json-schema
After thinking about it, I think you are correct that this would require parsing. This makes me think that the solution of doing this via the json-schema is the way to go. I generate from rust the json schema, so having this spec where I get libs for free seems the better solution. 
Sorry that the money in the bounty isn't enough. I don't care enough about this feature to add more. The money that was there was me just cleaning up one of my wallets. I will probably just close this issue request.
